/* Char_5C.h - Test Character
 *
 * D Provine, 20 Mar 2012
 * S Orsini 11 Dec 2020
 */

const byte Char_Test[10] = {
    0xff,     // ........
    0xff,     // ........
    0xff,     // .X......
    0xff,     // ..X.....
    0xff,     // ...X....
    0xff,     // ....X...
    0xff,     // .....X..
    0xff,     // ........
    0xff,     // ........
    0xff      // ........
};
